#!/usr/bin/env bash
# SPDX-License-Identifier: CC-BY-4.0

# Copyright © 2020 HolySpicoli (https://github.com/HolySpicoli/).
# Licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/).
# See LICENSE.md (https://github.com/HolySpicoli/WikimediaCommonsFile-Saskatchewan_COVID-19_Infection_Rates.svg/blob/master/LICENSE.md).

# Change to the directory of this script.
cd "$(dirname "$0")"

# Use 'xmllint' (http://xmlsoft.org/xmllint.html) to perform canonicalization (C14N) on the XML file generated by QGIS, for better version control.
xmllint --c14n Infection_Rate_Fill_Style.xml > Infection_Rate_Fill_Style.c14n.xml
